defaults:
  - model: default_model
  - data: default_data
  - loggers: default_loggers
  - callbacks: default_callbacks
  - trainer: default_trainer

project: pytorch_template
name: pytorch_template
log_dir: logs
seed: 42
